name: default
description: 📌 Pull Request 템플릿
labels: ['pr']

body:
  - type: textarea
    id: overview
    attributes:
      label: 📌 PR 개요
      description: 어떤 작업을 했는지 간단히 요약해주세요.
      placeholder: 예) 입력 검증 로직 개선 + 버튼 스타일 통일
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: ✅ 주요 변경 사항
      description: UI/로직 등 주요 변경 사항을 한두 줄로 요약해주세요.
      placeholder: 예) 날짜 선택 시 초기 포커싱 위치 수정 / 예약 시간대 API 응답 포맷 변경
    validations:
      required: true

  - type: input
    id: issue
    attributes:
      label: 🔗 관련 이슈
      description: 관련 이슈가 있다면 번호를 입력해주세요 (예: #12)
      placeholder: '#이슈번호'
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 🔍 체크리스트
      description: PR 작성 전에 아래 항목을 확인해주세요.
      options:
        - label: 정상 동작 확인
        - label: 빌드 오류 없음
        - label: 관련 이슈와 내용 일치
