name: iOS Build

on:
  pull_request:
    branches: [main]

jobs:
  ios-build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Install Pods
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install

      - name: Build iOS
        working-directory: ios
        run: xcodebuild -workspace SPOT.xcworkspace \
          -scheme SPOT \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath build

      - name: Archive App
        working-directory: ios
        run: xcodebuild -workspace SPOT.xcworkspace \
          -scheme SPOT \
          -sdk iphoneos \
          -configuration Release \
          -archivePath build/App.xcarchive \
          archive

      - name: Export IPA
        working-directory: ios
        run: |
          mkdir -p output
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath output \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ios-build
          path: ios/output/*.ipa
