name: Light PR Check

on:
  pull_request:
    branches: [main]

jobs:
  pr-check:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn install

      - name: CocoaPods Install
        working-directory: ios
        run: |
          sudo gem install cocoapods
          pod install

      - name: Check Scheme
        working-directory: ios
        run: |
          xcodebuild -workspace SPOT.xcworkspace -scheme SPOT -showBuildSettings
